apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mlpipeline-sar
rules:
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - get
      - watch
      - list
      - create
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelines
      - runs
      - tasks
      - taskruns
      - clustertasks
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
      - list