apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-runs
  namespace: REPLACE-USER
rules:
  - apiGroups:
      - pipelines.kubeflow.org
    resources:
      - runs
      - experiments
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
      - list
    resourceNames:
      - blabla
  - apiGroups:
      - pipelines.kubeflow.org
    resources:
      - runs
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
      - list
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
      - list