apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-operator
spec:
  template:
    spec:
      containers:
      - name: pytorch-operator
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: pytorch-config